version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '@types/node'
        versions:
          - 20.x
          - 22.x
      - dependency-name: 'eslint'
        versions:
          - 9.x
    groups:
      acorn:
        patterns:
          - 'acorn*'
      eslint-family:
        patterns:
          - 'eslint'
          - 'typescript-eslint'
          - 'eslint-config-prettier'
          - 'prettier'
